/**
 * Swagger/OpenAPI configuration
 * Generates API documentation
 */

import swaggerJsdoc from "swagger-jsdoc";

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Yield Optimization Agent API",
      version: "1.0.0",
      description: `
# Yield Optimization Agent API

An AI-powered API for discovering and accessing DeFi yield opportunities across multiple chains and protocols.

## Features

- 🤖 **AI-Powered Agent**: Natural language queries for yield opportunities
- 🔍 **Token Discovery**: Search and get detailed token information
- 🏦 **Protocol Discovery**: Find best staking opportunities across protocols
- 🛡️ **Safety Evaluation**: Comprehensive safety scoring for protocols
- 💰 **Transaction Generation**: Generate ready-to-sign transaction bundles
- 🌐 **Multi-Chain**: Supports Ethereum, Arbitrum, Optimism, Polygon, Base, Avalanche, and BNB Chain

## Getting Started

1. Obtain API access
2. Set up authentication (if required)
3. Start making requests to the endpoints below

## Safety Warnings

⚠️ **CRITICAL**: All transaction objects are generated by AI. Always verify:
- Token addresses on block explorer
- Protocol addresses on official protocol websites
- Transaction amounts and parameters
- Gas estimates

**This API does not provide financial advice. Always do your own research.**

## Rate Limits

- 100 requests per 15 minutes per IP address
- Batch queries limited to 10 queries maximum

## Support

For issues or questions, please contact support or visit our documentation.
      `,
      contact: {
        name: "API Support",
        email: "support@yieldagent.io",
      },
    },
    servers: [
      {
        url: "http://localhost:3000",
        description: "Development server",
      },
      {
        url: "https://api.yieldagent.io",
        description: "Production server (example)",
      },
    ],
    tags: [
      {
        name: "Agent",
        description: "AI agent endpoints for natural language queries",
      },
      {
        name: "Tokens",
        description: "Token information and search",
      },
      {
        name: "Protocols",
        description: "Protocol discovery and information",
      },
      {
        name: "Transactions",
        description: "Transaction bundle generation",
      },
      {
        name: "Chains",
        description: "Blockchain network information",
      },
    ],
    components: {
      schemas: {
        Error: {
          type: "object",
          properties: {
            success: {
              type: "boolean",
              example: false,
            },
            error: {
              type: "string",
              example: "Error message",
            },
            details: {
              type: "string",
              example: "Detailed error information",
            },
            timestamp: {
              type: "string",
              format: "date-time",
            },
          },
        },
        TokenInfo: {
          type: "object",
          properties: {
            name: { type: "string", example: "USD Coin" },
            symbol: { type: "string", example: "USDC" },
            address: { type: "string", example: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" },
            chain: { type: "string", example: "Ethereum" },
            chainId: { type: "number", example: 1 },
            decimals: { type: "number", example: 6 },
            price: { type: "number", example: 1.0 },
            marketCap: { type: "number", example: 30000000000 },
            verified: { type: "boolean", example: true },
          },
        },
        Protocol: {
          type: "object",
          properties: {
            address: { type: "string", example: "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9" },
            name: { type: "string", example: "Aave V3 USDC" },
            protocol: { type: "string", example: "aave-v3" },
            chainId: { type: "number", example: 1 },
            chainName: { type: "string", example: "Ethereum" },
            apy: { type: "number", example: 5.2 },
            tvl: { type: "number", example: 1000000000 },
            safetyScore: {
              type: "object",
              properties: {
                overall: { type: "string", enum: ["very_safe", "safe", "moderate", "risky"] },
                score: { type: "number", example: 85 },
                warnings: { type: "array", items: { type: "string" } },
              },
            },
          },
        },
        Transaction: {
          type: "object",
          properties: {
            to: { type: "string", example: "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9" },
            data: { type: "string", example: "0x..." },
            value: { type: "string", example: "0" },
            chainId: { type: "number", example: 1 },
            gasLimit: { type: "string", example: "200000" },
            type: { type: "string", example: "deposit" },
            safetyWarning: { type: "string" },
          },
        },
        Chain: {
          type: "object",
          properties: {
            id: { type: "number", example: 1 },
            name: { type: "string", example: "Ethereum" },
            chainName: { type: "string", example: "ethereum" },
          },
        },
      },
      securitySchemes: {
        ApiKeyAuth: {
          type: "apiKey",
          in: "header",
          name: "X-API-Key",
          description: "API key for authentication (if required)",
        },
      },
    },
  },
  apis: ["./src/api/routes.ts"], // Path to the API routes
};

export const swaggerSpec = swaggerJsdoc(options);

